from __future__ import annotations

from pathlib import Path


APP_ID = "lspdestroyer"
APP_TITLE = "LSPDestroyer"
DEFAULT_MAIN_GEOMETRY = "960x540"
DEFAULT_SETTINGS_GEOMETRY = "520x420"
STARTUP_NOTIFICATION = (
    "LSPDestroyer berjalan di system tray. Ctrl+O buka UI, Ctrl+F pilih file."
)
CONFIG_FILE_NAME = "config.json"
SUPPORTED_FILE_TYPES = [
    (
        "Text and code files",
        "*.txt *.py *.js *.ts *.tsx *.jsx *.json *.md *.html *.css *.java *.c "
        "*.cpp *.rs *.go *.php *.rb *.kt *.swift *.sql *.yaml *.yml *.toml *.ini",
    ),
    ("All files", "*.*"),
]

PACKAGE_ROOT = Path(__file__).resolve().parent
FONT_FILE = str(
    PACKAGE_ROOT
    / "assets"
    / "fonts"
    / "GoogleSans-VariableFont_GRAD,opsz,wght.ttf"
)
ICONS_DIR = PACKAGE_ROOT / "assets" / "icons"

MAIN_MIN_SIZE = (920, 520)
SETTINGS_MIN_SIZE = (520, 420)
WINDOW_ALPHA = 1.0
SETTINGS_ALPHA = 0.94
RESIZE_EDGE_WIDTH = 8
HOTKEY_DEBOUNCE_SECONDS = 0.18

MAIN_TRANSPARENT_COLOR = "#ff00ff"
MAIN_WINDOW_BACKGROUND = "#d0d0d0"
MAIN_PANEL_BACKGROUND = "#a9a9a9"
MAIN_PANEL_HEADER = "#9f9f9f"
MAIN_TEXT_PRIMARY = "#0f0f0f"
MAIN_TEXT_MUTED = "#2a2a2a"
MAIN_TEXT_SUBTLE = "#4b4b4b"
MAIN_DIVIDER = "#474747"
MAIN_BUTTON_HOVER = "#c0c0c0"
MAIN_BUTTON_ACTIVE = "#b6b6b6"
MAIN_TOOLTIP_BACKGROUND = "#121212"
MAIN_TOOLTIP_FOREGROUND = "#f4f4f4"
MAIN_SIDEBAR_WIDTH = 80
MAIN_HEADER_HEIGHT = 72
MAIN_CORNER_RADIUS = 32
MAIN_CONTENT_GAP = 12
MAIN_ICON_BUTTON_SIZE = 52
MAIN_ICON_CANVAS_SIZE = 46
MAIN_BRAND_LEFT_PADDING = 18
MAIN_PROGRESS_GAP = 88
MAIN_INFO_RIGHT_SLACK = 120
MAIN_PREVIEW_HEADER_HEIGHT = 56
MAIN_SELECT_BUTTON_BACKGROUND = "#d9d9d9"
MAIN_SELECT_BUTTON_ACTIVE = "#c7c7c7"

GRADIENT_PURPLE = "#7c3aed"
GRADIENT_BLUE = "#2563eb"
GRADIENT_GREEN = "#14b8a6"
WINDOW_BACKGROUND = "#07111d"
SURFACE_BACKGROUND = "#0a1524"
SURFACE_BACKGROUND_ALT = "#0d1b2f"
CARD_BACKGROUND = "#0c1a2d"
CARD_BACKGROUND_ALT = "#10233a"
CARD_BORDER = "#8be9ff"
TEXT_PRIMARY = "#eff6ff"
TEXT_MUTED = "#94a3b8"
TEXT_SUBTLE = "#7c8ea7"
BUTTON_PRIMARY = "#14243b"
BUTTON_PRIMARY_ACTIVE = "#1b3558"
BUTTON_ACCENT = "#302064"
BUTTON_ACCENT_ACTIVE = "#42319a"
PREVIEW_BACKGROUND = "#09121f"
PREVIEW_FOREGROUND = "#e5f0ff"
SCROLLBAR_TROUGH = "#0a1220"
SCROLLBAR_THUMB = "#2b4767"
SLIDER_PANEL = "#0a1322"
SLIDER_TRACK = "#060d18"
SLIDER_THUMB = "#4d7cc7"
SLIDER_THUMB_ACTIVE = "#8be9ff"
SLIDER_BORDER = "#5fb9e5"
GOOGLE_SANS_FAMILY = "Google Sans"
FONT_TITLE = (GOOGLE_SANS_FAMILY, 20, "bold")
FONT_SUBTITLE = (GOOGLE_SANS_FAMILY, 10)
FONT_BODY = (GOOGLE_SANS_FAMILY, 10)
FONT_CAPTION = (GOOGLE_SANS_FAMILY, 9, "bold")
FONT_CODE = ("Consolas", 11)
FONT_CODE_LARGE = (GOOGLE_SANS_FAMILY, 13, "bold")
FONT_CARD_TITLE = (GOOGLE_SANS_FAMILY, 12, "bold")
FONT_SETTINGS_TITLE = (GOOGLE_SANS_FAMILY, 18, "bold")
FONT_BUTTON = (GOOGLE_SANS_FAMILY, 10, "bold")
FONT_BRAND_TITLE = (GOOGLE_SANS_FAMILY, 24, "bold")
FONT_BRAND_SUBTITLE = (GOOGLE_SANS_FAMILY, 12, "bold")
FONT_META_LABEL = (GOOGLE_SANS_FAMILY, 11, "bold")
FONT_META_VALUE = (GOOGLE_SANS_FAMILY, 11)
FONT_PREVIEW_TITLE = (GOOGLE_SANS_FAMILY, 15, "bold")
FONT_TOOLTIP = (GOOGLE_SANS_FAMILY, 10, "bold")
